//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: System.Reflection.AssemblyTitle("ado")]
[assembly: System.Reflection.AssemblyDescription("Example program for storing data in database  using Entity Framework")]
[assembly: System.Reflection.AssemblyCompany("RIT")]
[assembly: System.Reflection.AssemblyProduct("eTester")]
[assembly: System.Reflection.AssemblyCopyright("Copyright RIT")]
[assembly: System.Runtime.InteropServices.ComVisible(false)]
[assembly: System.CLSCompliant(true)]
[assembly: System.Reflection.AssemblyInformationalVersion("1.0.1.7b09957")]
[assembly: System.Reflection.AssemblyVersion("1.0.1")]
[assembly: System.Reflection.AssemblyFileVersion("1.0.1")]


