//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado
{
    using System;
    using System.Collections.Generic;
    
    public partial class Calibration
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Calibration()
        {
            this.CalibrationDatas = new HashSet<CalibrationData>();
        }
    
        public string SerialNo { get; set; }
        public string MAC { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> BatchId { get; set; }
    
        public virtual Batch Batch { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CalibrationData> CalibrationDatas { get; set; }
    }
}
