//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ado
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class RIT_QAEntities : DbContext
    {
        public RIT_QAEntities()
            : base("name=RIT_QAEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Batch> Batches { get; set; }
        public virtual DbSet<Calibration> Calibrations { get; set; }
        public virtual DbSet<ElectricalTest> ElectricalTests { get; set; }
        public virtual DbSet<CalibrationData> CalibrationDatas { get; set; }
    }
}
